package dotpath_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/afeiship/go-dotpath"
)

func TestNewDotIO(t *testing.T) {
	// Test creating adapters with different formats
	jsonAdapter := dotpath.NewDotIO(dotpath.JSON)
	if jsonAdapter.GetFormat() != dotpath.JSON {
		t.Errorf("Expected JSON format, got %v", jsonAdapter.GetFormat())
	}

	yamlAdapter := dotpath.NewDotIO(dotpath.YAML)
	if yamlAdapter.GetFormat() != dotpath.YAML {
		t.Errorf("Expected YAML format, got %v", yamlAdapter.GetFormat())
	}
}

func TestNewDotIOWithData(t *testing.T) {
	data := map[string]any{
		"test": "value",
		"number": 42,
	}

	jsonAdapter := dotpath.NewDotIOWithData(data, dotpath.JSON)
	if jsonAdapter.GetString("test") != "value" {
		t.Errorf("Expected 'value', got '%s'", jsonAdapter.GetString("test"))
	}

	if jsonAdapter.GetInt("number") != 42 {
		t.Errorf("Expected 42, got %d", jsonAdapter.GetInt("number"))
	}
}

func TestDotIOLoadFromBytes_JSON(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)

	jsonData := []byte(`{"name": "test", "value": 123, "enabled": true}`)

	if err := adapter.LoadFromBytes(jsonData); err != nil {
		t.Fatalf("Failed to load JSON bytes: %v", err)
	}

	if name := adapter.GetString("name"); name != "test" {
		t.Errorf("Expected 'test', got '%s'", name)
	}

	if value := adapter.GetInt("value"); value != 123 {
		t.Errorf("Expected 123, got %d", value)
	}

	if enabled := adapter.GetBool("enabled"); !enabled {
		t.Errorf("Expected true, got %v", enabled)
	}
}

func TestDotIOLoadFromBytes_YAML(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.YAML)

	yamlData := []byte(`
name: test
value: 123
enabled: true
config:
  timeout: 30
  retries: 3
`)

	if err := adapter.LoadFromBytes(yamlData); err != nil {
		t.Fatalf("Failed to load YAML bytes: %v", err)
	}

	if name := adapter.GetString("name"); name != "test" {
		t.Errorf("Expected 'test', got '%s'", name)
	}

	if value := adapter.GetInt("value"); value != 123 {
		t.Errorf("Expected 123, got %d", value)
	}

	if enabled := adapter.GetBool("enabled"); !enabled {
		t.Errorf("Expected true, got %v", enabled)
	}

	if timeout := adapter.GetInt("config.timeout"); timeout != 30 {
		t.Errorf("Expected 30, got %d", timeout)
	}
}

func TestDotIOLoadFromString(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)

	jsonString := `{"app": {"name": "demo", "version": "1.0"}}`

	if err := adapter.LoadFromString(jsonString); err != nil {
		t.Fatalf("Failed to load JSON string: %v", err)
	}

	if name := adapter.GetString("app.name"); name != "demo" {
		t.Errorf("Expected 'demo', got '%s'", name)
	}

	if version := adapter.GetString("app.version"); version != "1.0" {
		t.Errorf("Expected '1.0', got '%s'", version)
	}
}

func TestDotIOLoadFromFile(t *testing.T) {
	// Test JSON
	jsonAdapter := dotpath.NewDotIO(dotpath.JSON)
	tempDir := t.TempDir()
	jsonFile := filepath.Join(tempDir, "test.json")

	jsonContent := `{"service": "api", "port": 8080}`
	if err := os.WriteFile(jsonFile, []byte(jsonContent), 0644); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	if err := jsonAdapter.LoadFromFile(jsonFile); err != nil {
		t.Fatalf("Failed to load JSON from file: %v", err)
	}

	if service := jsonAdapter.GetString("service"); service != "api" {
		t.Errorf("Expected 'api', got '%s'", service)
	}

	if port := jsonAdapter.GetInt("port"); port != 8080 {
		t.Errorf("Expected 8080, got %d", port)
	}

	// Test YAML
	yamlAdapter := dotpath.NewDotIO(dotpath.YAML)
	yamlFile := filepath.Join(tempDir, "test.yaml")

	yamlContent := "service: api\nport: 8080\n"
	if err := os.WriteFile(yamlFile, []byte(yamlContent), 0644); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	if err := yamlAdapter.LoadFromFile(yamlFile); err != nil {
		t.Fatalf("Failed to load YAML from file: %v", err)
	}

	if service := yamlAdapter.GetString("service"); service != "api" {
		t.Errorf("Expected 'api', got '%s'", service)
	}

	if port := yamlAdapter.GetInt("port"); port != 8080 {
		t.Errorf("Expected 8080, got %d", port)
	}
}

func TestDotIOLoadFromFileNotFound(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)

	if err := adapter.LoadFromFile("/nonexistent/file.json"); err == nil {
		t.Error("Expected error for nonexistent file")
	}
}

func TestDotIOToBytes_JSON(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)
	adapter.Set("name", "test")
	adapter.Set("value", 42)

	bytes, err := adapter.ToBytes()
	if err != nil {
		t.Fatalf("Failed to convert to bytes: %v", err)
	}

	// Verify it's valid JSON by loading it back
	newAdapter := dotpath.NewDotIO(dotpath.JSON)
	if err := newAdapter.LoadFromBytes(bytes); err != nil {
		t.Fatalf("Failed to load generated bytes: %v", err)
	}

	if name := newAdapter.GetString("name"); name != "test" {
		t.Errorf("Expected 'test', got '%s'", name)
	}
}

func TestDotIOToBytes_YAML(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.YAML)
	adapter.Set("name", "test")
	adapter.Set("value", 42)

	bytes, err := adapter.ToBytes()
	if err != nil {
		t.Fatalf("Failed to convert to bytes: %v", err)
	}

	// Verify it's valid YAML by loading it back
	newAdapter := dotpath.NewDotIO(dotpath.YAML)
	if err := newAdapter.LoadFromBytes(bytes); err != nil {
		t.Fatalf("Failed to load generated bytes: %v", err)
	}

	if name := newAdapter.GetString("name"); name != "test" {
		t.Errorf("Expected 'test', got '%s'", name)
	}
}

func TestDotIOToString(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)
	adapter.Set("message", "hello world")

	str, err := adapter.ToString()
	if err != nil {
		t.Fatalf("Failed to convert to string: %v", err)
	}

	if str == "" {
		t.Error("Expected non-empty string")
	}

	// Verify it's valid JSON
	newAdapter := dotpath.NewDotIO(dotpath.JSON)
	if err := newAdapter.LoadFromString(str); err != nil {
		t.Fatalf("Failed to load generated string: %v", err)
	}

	if message := newAdapter.GetString("message"); message != "hello world" {
		t.Errorf("Expected 'hello world', got '%s'", message)
	}
}

func TestDotIOSaveToFile(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)
	adapter.Set("app", "demo")
	adapter.Set("version", "2.0.0")

	tempDir := t.TempDir()
	tempFile := filepath.Join(tempDir, "output.json")

	if err := adapter.SaveToFile(tempFile); err != nil {
		t.Fatalf("Failed to save to file: %v", err)
	}

	// Verify file exists
	if _, err := os.Stat(tempFile); os.IsNotExist(err) {
		t.Error("Output file was not created")
	}

	// Load and verify content
	loadedAdapter := dotpath.NewDotIO(dotpath.JSON)
	if err := loadedAdapter.LoadFromFile(tempFile); err != nil {
		t.Fatalf("Failed to load saved file: %v", err)
	}

	if app := loadedAdapter.GetString("app"); app != "demo" {
		t.Errorf("Expected 'demo', got '%s'", app)
	}
}

func TestDotIOSetFormat(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)
	adapter.Set("test", "value")

	// Change format to YAML
	adapter.SetFormat(dotpath.YAML)

	if adapter.GetFormat() != dotpath.YAML {
		t.Errorf("Expected YAML format, got %v", adapter.GetFormat())
	}

	// Output should now be in YAML format
	str, _ := adapter.ToString()
	if str[0] != 't' && str[:4] != "test" { // YAML format
		t.Errorf("Expected YAML format output, got: %s", str[:20])
	}
}

func TestDotIOConvenienceMethods(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)
	adapter.Set("string", "test")
	adapter.Set("number", 42)
	adapter.Set("boolean", true)
	adapter.Set("float", 3.14)

	// Test Get
	if val, exists := adapter.Get("string"); !exists || val != "test" {
		t.Error("Get method failed")
	}

	// Test GetString
	if str := adapter.GetString("string"); str != "test" {
		t.Errorf("Expected 'test', got '%s'", str)
	}

	// Test GetInt
	if num := adapter.GetInt("number"); num != 42 {
		t.Errorf("Expected 42, got %d", num)
	}

	// Test GetBool
	if b := adapter.GetBool("boolean"); !b {
		t.Errorf("Expected true, got %v", b)
	}

	// Test GetFloat64
	if f := adapter.GetFloat64("float"); f != 3.14 {
		t.Errorf("Expected 3.14, got %f", f)
	}

	// Test Has
	if !adapter.Has("string") {
		t.Error("Has method should return true for existing key")
	}

	if adapter.Has("nonexistent") {
		t.Error("Has method should return false for non-existing key")
	}

	// Test Update
	updates := map[string]any{
		"new": "value",
		"number": 100, // Should overwrite
	}
	adapter.Update(updates)

	if adapter.GetString("new") != "value" {
		t.Error("Update failed to add new key")
	}

	if adapter.GetInt("number") != 100 {
		t.Error("Update failed to overwrite existing key")
	}

	// Test Data
	data := adapter.Data()
	if data["string"] != "test" {
		t.Error("Data method failed")
	}
}

func TestDotIODotPath(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)
	adapter.Set("nested.value", "test")

	dp := adapter.DotPath()

	// Test that we can use the original DotPath methods
	if val := dp.GetString("nested.value"); val != "test" {
		t.Errorf("Expected 'test', got '%s'", val)
	}
}

func TestLoadJSONAdapter(t *testing.T) {
	tempDir := t.TempDir()
	tempFile := filepath.Join(tempDir, "config.json")

	content := `{"service": "test", "port": 3000}`
	if err := os.WriteFile(tempFile, []byte(content), 0644); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	adapter, err := dotpath.LoadJSONAdapter(tempFile)
	if err != nil {
		t.Fatalf("Failed to load JSON adapter: %v", err)
	}

	if adapter.GetFormat() != dotpath.JSON {
		t.Error("Expected JSON format")
	}

	if service := adapter.GetString("service"); service != "test" {
		t.Errorf("Expected 'test', got '%s'", service)
	}
}

func TestLoadYAMLAdapter(t *testing.T) {
	tempDir := t.TempDir()
	tempFile := filepath.Join(tempDir, "config.yaml")

	content := "service: test\nport: 3000\n"
	if err := os.WriteFile(tempFile, []byte(content), 0644); err != nil {
		t.Fatalf("Failed to write test file: %v", err)
	}

	adapter, err := dotpath.LoadYAMLAdapter(tempFile)
	if err != nil {
		t.Fatalf("Failed to load YAML adapter: %v", err)
	}

	if adapter.GetFormat() != dotpath.YAML {
		t.Error("Expected YAML format")
	}

	if service := adapter.GetString("service"); service != "test" {
		t.Errorf("Expected 'test', got '%s'", service)
	}
}

func TestDotIOInvalidJSON(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.JSON)

	invalidJSON := []byte(`{"invalid": json}`)
	if err := adapter.LoadFromBytes(invalidJSON); err == nil {
		t.Error("Expected error for invalid JSON")
	}
}

func TestDotIOInvalidYAML(t *testing.T) {
	adapter := dotpath.NewDotIO(dotpath.YAML)

	invalidYAML := []byte(`invalid: yaml: [unclosed`)
	if err := adapter.LoadFromBytes(invalidYAML); err == nil {
		t.Error("Expected error for invalid YAML")
	}
}